-- MySQL Script generated by MySQL Workbench
-- Sun Jun 25 23:35:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`user` (
  `name` VARCHAR(32) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `salt` VARCHAR(32) NOT NULL,
  `role` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`name`, `username`),
  INDEX `idx_username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`admins` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(32) NOT NULL,
  `user_username` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`, `user_name`, `user_username`),
  INDEX `fk_admins_user_idx` (`user_username` ASC, `user_name` ASC) VISIBLE,
  CONSTRAINT `fk_admins_user`
    FOREIGN KEY (`user_username` , `user_name`)
    REFERENCES `cinema`.`user` (`username` , `name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`cinemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`cinemas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `is_3d` TINYINT NOT NULL,
  `seats` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`content_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`content_admins` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(32) NOT NULL,
  `user_username` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`, `user_name`, `user_username`),
  INDEX `fk_content_admins_user_idx` (`user_username` ASC, `user_name` ASC) VISIBLE,
  CONSTRAINT `fk_content_admins_user`
    FOREIGN KEY (`user_username` , `user_name`)
    REFERENCES `cinema`.`user` (`username` , `name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`customers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(32) NOT NULL,
  `user_username` VARCHAR(32) NOT NULL,
  `reservations_made` INT NOT NULL,
  PRIMARY KEY (`ID`, `user_name`, `user_username`),
  INDEX `fk_customers_user_idx` (`user_username` ASC, `user_name` ASC) VISIBLE,
  CONSTRAINT `fk_customers_user`
    FOREIGN KEY (`user_username` , `user_name`)
    REFERENCES `cinema`.`user` (`username` , `name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`movies` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(48) NOT NULL,
  `category` VARCHAR(32) NOT NULL,
  `description` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`, `title`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`presentations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`presentations` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `movies_ID` INT NOT NULL,
  `movies_title` VARCHAR(48) NOT NULL,
  `cinemas_ID` INT NOT NULL,
  `start_date` VARCHAR(32) NOT NULL,
  `number_of_reservations` INT NOT NULL,
  `is_available` TINYINT NOT NULL,
  `total_seats` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_presentations_cinemas_ID_idx` (`cinemas_ID` ASC) VISIBLE,
  INDEX `fk_presentations_movies_title_idx` (`movies_title` ASC) VISIBLE,
  CONSTRAINT `fk_presentations_cinemas`
    FOREIGN KEY (`cinemas_ID`)
    REFERENCES `cinema`.`cinemas` (`ID`),
  CONSTRAINT `fk_presentations_movies_ID`
    FOREIGN KEY (`movies_ID` , `movies_title`)
    REFERENCES `cinema`.`movies` (`ID` , `title`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`reservations` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `presentations_movies_ID` INT NOT NULL,
  `presentations_movies_title` VARCHAR(48) NOT NULL,
  `presentations_cinemas_ID` INT NOT NULL,
  `customers_ID` INT NOT NULL,
  `number_of_seats` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_reseervations_customers_idx` (`customers_ID` ASC) VISIBLE,
  INDEX `fk_reservations_presentations1_idx` (`presentations_movies_ID` ASC, `presentations_movies_title` ASC) VISIBLE,
  INDEX `fk_reservations_presentations2_idx` (`presentations_cinemas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_reseervations_customers`
    FOREIGN KEY (`customers_ID`)
    REFERENCES `cinema`.`customers` (`ID`),
  CONSTRAINT `fk_reservations_presentations1`
    FOREIGN KEY (`presentations_movies_ID` , `presentations_movies_title`)
    REFERENCES `cinema`.`presentations` (`movies_ID` , `movies_title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_presentations2`
    FOREIGN KEY (`presentations_cinemas_ID`)
    REFERENCES `cinema`.`presentations` (`cinemas_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
